### ISSUE TITLE
[Suggestion] Migrate this plugin to use as a dynamic plugin on backstage

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-plugins#23]
## Suggestion

Migrate this plugin to be a dynamic plugin

## Information from Tom Coufal

What a developer should do to convert a plugin to become a dynamic plugin ?

> See steps in https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md. The steps differ between backend and frontend plugins.

Can such a plugin be tested locally (= using janus showcase or backstage upstream)?

> It is possible using Janus Showcase, Backstage upstream does not have yet all dynamic plugins features available, we're working towards getting it in there. Local deployment using showcase is described in the docs as well here (aka just drop the plugin into a specific folder): https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#local-configuration
Also.. it may interest you, I did an user/integrator perspective enablement session on dynamic plugins in December. Here's the recording and slides:
https://drive.google.com/file/d/1KLDNrayzF2RoPV_JzahikfyfRGvEmwj5/view?usp=drive_link
https://docs.google.com/presentation/d/137dazgC1YlSffhJuTLx2_xubTwiYBYaucds2GtciHkA/edit?usp=drive_link

And demos: https://github.com/tumido/janus-dynamic-plugins-enablement-demo

**Comment by cmoulliard** [comment]
## Steps followed + changes to play with the [tutorial](https://github.com/tumido/janus-dynamic-plugins-enablement-demo) of Tom Foudal - backend part

```
TERMINAL 1
git clone https://github.com/tumido/janus-dynamic-plugins-enablement-demo.git
cd janus-dynamic-plugins-enablement-demo

TERMINAL 2
NPM_ACCOUNT=cmoulliard
DEMO_DIR="/Users/cmoullia/code/janus-idp/janus-dynamic-plugins-enablement-demo/02_backend_plugin"

cd $(mktemp -d)
npx @backstage/cli@latest new --scope @$NPM_ACCOUNT --select backend-plugin --option id=demo
cd backstage-plugin-demo-backend

md src/dynamic
cp $DEMO_DIR/src/dynamic/index.ts src/dynamic/index.ts
cp $DEMO_DIR/app-config.yaml .

echo "export * from './dynamic/index';" >> src/index.ts

npm pkg delete "private"
yarn add @backstage/backend-dynamic-feature-service
yarn add -D @janus-idp/cli

npm pkg set "files[1]"="dist-dynamic/*.*"
npm pkg set "files[2]"="dist-dynamic/dist/**"
npm pkg set "files[3]"="dist-dynamic/alpha/*"
npm pkg set "scripts.export-dynamic"="janus-cli package export-dynamic-plugin"
npm pkg set "scripts.postversion"="yarn run export-dynamic"

!! Change the import within src/dynamic/index.ts to use
import { BackendDynamicPluginInstaller } from '@backstage/backend-dynamic-feature-service';

yarn tsc
yarn build
yarn export-dynamic
yarn publish

npm info @$NPM_ACCOUNT/backstage-plugin-demo-backend
```
Finally, I edited the value file of the helm chart `global/dynamic/plugins`: https://github.com/redhat-developer/rhdh-chart/blob/main/charts/backstage/values.yaml#L14
to include our dynamic plugin

```yaml
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - integrity: "sha512-B173sefZYMFOfWpIp5Qh9faLBbWHVmZ0WzOybnBVk6qzDzRDQYbqU8bCgzfK16qsfI7gdjYTYNhdC/wI+GhSOg=="
        package: https://registry.npmjs.org/@cmoulliard/backstage-plugin-demo-backend/-/backstage-plugin-demo-backend-0.1.1.tgz
        disabled: false
```

Issue: https://github.com/tumido/janus-dynamic-plugins-enablement-demo/issues/1

**Comment by cmoulliard** [comment]
Front end part 

```bash
TERMINAL 1
git clone https://github.com/tumido/janus-dynamic-plugins-enablement-demo.git
cd janus-dynamic-plugins-enablement-demo

TERMINAL 2
NPM_ACCOUNT=cmoulliard
DEMO_DIR="/Users/cmoullia/code/janus-idp/janus-dynamic-plugins-enablement-demo/01_frontend_plugin"

mkdir ~/temp/dynamic-plugin && cd ~/temp/dynamic-plugin

npx @backstage/cli@latest new --scope @$NPM_ACCOUNT --select plugin --option id=demo
cd backstage-plugin-demo

yarn add -D react@^17.0.2 react-dom@^17.0.2 react-router-dom@^6.20.0
yarn add @backstage/plugin-catalog-react @material-ui/icons@4.11.3

cp -r $DEMO_DIR/src/components/DemoEntityCard ./src/components
cp $DEMO_DIR/app-config.yaml .
cp $DEMO_DIR/config.d.ts .
echo "export { DemoEntityCard } from './components/DemoEntityCard';" >> ./src/index.ts
echo "export { default as DemoIcon } from '@material-ui/icons/EmojiPeople';" >> ./src/index.ts

npm pkg set "configSchema"="config.d.ts"
npm pkg delete "private"
```

Set up as dynamic plugin
```bash
yarn add -D @janus-idp/cli
npm pkg set "files[1]"="dist-scalprum"
npm pkg set "scripts.export-dynamic"="janus-cli package export-dynamic-plugin"
npm pkg set "scripts.postversion"="yarn run export-dynamic"
```
Build and publish

```bash
yarn tsc
yarn build
yarn export-dynamic
yarn publish
npm info @$NPM_ACCOUNT/backstage-plugin-demo
```
Edit the value file of the helm chart `global/dynamic/plugins`: https://github.com/redhat-developer/rhdh-chart/blob/main/charts/backstage/values.yaml#L14
to include our dynamic plugin

```yaml
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - integrity: "sha512-KxNqPf1psKAQdYYf0ZpfsSTYHQLMfBsJZlFqhqPwYX2/efq5/UWYpvtTwBRwDz8GhrEYK2pCMSreyAADPKkg3A=="
        package: https://registry.npmjs.org/@cmoulliard/backstage-plugin-demo/-/backstage-plugin-demo-0.1.2.tgz
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              cmoulliard.backstage-plugin-demo:
                appIcons:
                  - name: demoIcon
                    importName: DemoIcon
                dynamicRoutes:
                  - importName: DemoPage
                    menuItem:
                      icon: demoIcon
                      text: This is Demo
                    path: /demo
                mountPoints:
                  - mountPoint: entity.page.overview/cards
                    importName: DemoEntityCard
                    config:
                      layout:
                        gridColumnEnd:
                          lg: "span 4"
                          md: "span 6"
                          xs: "span 12"
                      props:
                        title: Custom title
                      if:
                        anyOf:
                          - isKind: component
```
