### ISSUE TITLE
Extension list filtering is broken

### ISSUE THREAD

**Issue by iocanel** [q-shift/backstage-plugins#38]
Adding something like:

```
        extensions:
          title: Alternative Extensions
          type: array
          description: The list of alternative extensions
          ui:field: QuarkusExtensionList
          ui:options:
            filter:
              extensions:
                - io.quarkus:quarkus-resteasy-reactive-jackson
                - io.quarkus:quarkus-smallrye-openapi
                - io.quarkus:quarkus-smallrye-graphql
                - io.quarkus:quarkus-hibernate-orm-rest-data-panache
```

Should only display the provided extensions, however this seems to be broken at the moment.

**Note**: Extensions may be provided using wildcards

**Comment by cmoulliard** [comment]
> Should only display the selected templates, however this seems to be broken at the moment.

It should only display the extensions set as default values BUT will it be possible to select more ? @iocanel

**Comment by iocanel** [comment]
No, it should prevent users from seeing or selecting anything that does not match the filters.

**Comment by cmoulliard** [comment]
> filter:
>               extensions:

Was this filter parameter working before ? Which project ? @iocanel

**Comment by cmoulliard** [comment]
> No, it should prevent users from seeing or selecting anything that does not match the filters.

Why don't we then, int this case, convert the existing ui into an enum as you force the user to use the fixed list of extensions instead of what we got from code.quarkus.io ? @iocanel

**Comment by iocanel** [comment]
Because this approach allows us to use wildcards, filtering by category and filtering by keyword.

**Comment by cmoulliard** [comment]
> Should only display the selected templates

Can you elaborate a little as the wording seems wrong ? Why do you speak about templates here ? @iocanel

**Comment by cmoulliard** [comment]
The error which is reported by the browser's console is about =>

![Screenshot 2024-02-22 at 14 36 15](https://github.com/q-shift/backstage-plugins/assets/463790/30c8655d-898f-4a86-91a2-6ac7c7efc2fe)
![Screenshot 2024-02-22 at 14 37 17](https://github.com/q-shift/backstage-plugins/assets/463790/6ad418f3-5b46-4de5-887e-c7932de5c4fa)

This is because the `ui:options` of the template don't specify the `codeQuarkusUrl`. This problem is fixed if we specify it like this:
```
          ui:options:
            codeQuarkusUrl: https://code.quarkus.io
            filter:
              extensions:
                - io.quarkus:quarkus-resteasy-reactive-jackson
                - io.quarkus:quarkus-smallrye-openapi
                - io.quarkus:quarkus-smallrye-graphql
                - io.quarkus:quarkus-hibernate-orm-rest-data-panache
```
@iocanel
